spring:
  application:
    name: hello-application
  redis:
    cluster:
      nodes: 121.37.23.148:7002,121.37.23.148:7004,121.37.23.148:7001,121.37.23.148:7003,121.37.23.148:7000,121.37.23.148:7005
    password: qT$4EfA1234561TvAk*N6
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081